<a href="https://colab.research.google.com/github/mohameda1011/library-data-analysis/blob/main/Copy_of_Revision_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Library Management Analysis

A local library wants to better understand how its books are being borrowed. You are given a dataset containing information about books, members, and borrowing records. Your task is to analyze the dataset and produce useful insights that could help the library improve its services.

### Requirements

* Create a GitHub repository for the project and use Git throughout your development with meaningful commits.
* Include a `README.md` explaining the project, dataset, and how to run your code.
* Write clean, readable Python code and use functions whenever appropriate.
* Load the dataset using Pandas.
* Explore the dataset by displaying enough information to understand its structure before beginning the analysis.
* If the dataset contains any issues that prevent your analysis from running correctly, make only the minimum changes required to continue. You are not expected to perform a complete data cleaning process.
* Calculate the probability of randomly selecting:

  * A borrowed book from a specific genre.
  * A member belonging to a specific membership type.
  * A borrowing record that satisfies two conditions of your choice.
* Using Pandas, answer the following:

  * Find the category with the highest and lowest number of borrowings.
  * Determine which members borrow books most frequently.
  * Compare borrowing activity between different membership types.
  * Analyze how borrowing changes across publication years.
  * Identify the most popular authors.
  * Find the books that have never been borrowed.
  * Compare the average borrowing duration across genres.
  * Show the distribution of books across genres.
  * Analyze monthly borrowing trends (if borrowing dates are available).
  * Present three additional insights of your choice.
* Using NumPy, answer the following:

  * Convert one or more numerical columns into NumPy arrays.
  * Identify the highest and lowest values in a numerical column.
  * Use boolean indexing to filter a subset of the data.
  * Sort a NumPy array and display the result.
  * Perform at least one vectorized calculation to create a new numerical result or metric.
* Produce a final summary highlighting the most important insights from your analysis.

Your project should be well-structured and reproducible. Anyone running your code should be able to obtain the same results without modifying the source code.

In [2]:
from google.colab import files
uploaded = files.upload()

Saving members.csv to members.csv
Saving borrowings.csv to borrowings.csv
Saving books.csv to books.csv

In [3]:
import pandas as pd
import numpy as np

df1 = pd.read_csv("books.csv")
df2 = pd.read_csv("borrowings.csv")
df3 = pd.read_csv("members.csv")

In [4]:
df1.head()

,BookID,Title,Author,Genre,PublicationYear,Publisher,Pages,Language,CopiesAvailable
0,B001,Book 1,George Orwell,Science Fiction,1986,Pearson,401,English,3
1,B002,Book 2,Brandon Sanderson,Mystery,1991,Pearson,678,English,1
2,B003,Book 3,Jane Austen,Programming,1987,Penguin,215,English,3
3,B004,Book 4,Brandon Sanderson,Business,2023,Penguin,694,English,3
4,B005,Book 5,Mark Lee,Business,2011,HarperCollins,579,English,4

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   BookID           400 non-null    object
 1   Title            400 non-null    object
 2   Author           400 non-null    object
 3   Genre            400 non-null    object
 4   PublicationYear  400 non-null    int64
 5   Publisher        400 non-null    object
 6   Pages            400 non-null    int64
 7   Language         400 non-null    object
 8   CopiesAvailable  400 non-null    int64
dtypes: int64(3), object(6)
memory usage: 28.3+ KB

In [7]:
print(df1.isnull().sum())
print(df1.shape)

BookID             0
Title              0
Author             0
Genre              0
PublicationYear    0
Publisher          0
Pages              0
Language           0
CopiesAvailable    0
dtype: int64
(400, 9)

In [8]:
df2.head()

  BorrowID MemberID BookID  BorrowDate  ReturnDate
0   BR0001     M063   B143  2025-05-17  2025-06-07
1   BR0002     M101   B159  2024-10-14  2024-11-12
2   BR0003     M140   B077  2025-07-31  2025-08-09
3   BR0004     M007   B385  2026-02-25  2026-03-17
4   BR0005     M054   B184  2025-04-17  2025-05-12

In [9]:
df2['BorrowDate'] = pd.to_datetime(df2['BorrowDate'])
df2['ReturnDate'] = pd.to_datetime(df2['ReturnDate'])

In [10]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   BorrowID    2000 non-null   object
 1   MemberID    2000 non-null   object
 2   BookID      2000 non-null   object
 3   BorrowDate  2000 non-null   datetime64[ns]
 4   ReturnDate  2000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), object(3)
memory usage: 78.3+ KB

In [11]:
print(df2.isnull().sum())
print(df2.shape)

BorrowID      0
MemberID      0
BookID        0
BorrowDate    0
ReturnDate    0
dtype: int64
(2000, 5)

In [12]:
df3.head()

  MemberID      Name MembershipType  Age  Gender    JoinDate
0     M001  Member 1        Student   47    Male  2025-02-18
1     M002  Member 2         Public   47  Female  2022-02-14
2     M003  Member 3         Public   43  Female  2022-01-07
3     M004  Member 4        Student   65    Male  2025-03-30
4     M005  Member 5        Student   22    Male  2024-05-17

In [13]:
df3['JoinDate'] = pd.to_datetime(df3['JoinDate'])

In [14]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   MemberID        150 non-null    object
 1   Name            150 non-null    object
 2   MembershipType  150 non-null    object
 3   Age             150 non-null    int64
 4   Gender          150 non-null    object
 5   JoinDate        150 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 7.2+ KB

In [15]:
print(df3.isnull().sum())
print(df3.shape)

MemberID          0
Name              0
MembershipType    0
Age               0
Gender            0
JoinDate          0
dtype: int64
(150, 6)

In [16]:
# Calculate the probability of randomly selecting a borrowed book from a specific genre.(Business)
borr_book = pd.merge(df1, df2, on='BookID', how='inner')

borr_books = len(borr_book)
Business_borr_books = len(borr_book[borr_book['Genre'] == 'Business'])

probability1 = Business_borr_books / borr_books
print(f'the probability of randomly selecting a borrowed book from business is {probability1:.2%}')

the probability of randomly selecting a borrowed book from business is 6.05%

In [17]:
# Calculate the probability of randomly selecting a member belonging to a specific membership type (Student)
total_mem = len(df3)

stu_mem = len(df3[df3['MembershipType'] == 'Student'])

probability2 = stu_mem / total_mem
print(f'the probability of randomly selecting a student is {probability2:.2%}')

the probability of randomly selecting a student is 60.00%

In [18]:
# Calculate the probability of randomly selecting a borrowing record that satisfies two conditions of your choice. (a student and borrow mystery book)
df_full = pd.merge(borr_book, df3, on='MemberID', how='inner')

total_rec = len(df_full)
bor_rec = len(df_full[ (df_full['MembershipType'] == 'Student') & (df_full['Genre'] == 'Mystery') ])

probability3 = bor_rec / total_rec
print(f'the probability of randomly selecting a borrowing record that satisfies the two conditions: a student and borrow mystery book is: {probability3:.2%}')

the probability of randomly selecting a borrowing record that satisfies the two conditions: a student and borrow mystery book is: 15.35%

In [19]:
df_full.head()

,BookID,Title,Author,Genre,PublicationYear,Publisher,Pages,Language,CopiesAvailable,BorrowID,MemberID,BorrowDate,ReturnDate,Name,MembershipType,Age,Gender,JoinDate
0,B001,Book 1,George Orwell,Science Fiction,1986,Pearson,401,English,3,BR0095,M025,2024-04-03,2024-04-28,Member 25,Student,56,Male,2024-07-03
1,B001,Book 1,George Orwell,Science Fiction,1986,Pearson,401,English,3,BR0778,M102,2025-04-08,2025-04-25,Member 102,Student,31,Female,2023-07-10
2,B002,Book 2,Brandon Sanderson,Mystery,1991,Pearson,678,English,1,BR0080,M149,2025-05-14,2025-05-27,Member 149,Faculty,38,Male,2024-03-26
3,B002,Book 2,Brandon Sanderson,Mystery,1991,Pearson,678,English,1,BR0144,M131,2024-04-28,2024-05-08,Member 131,Faculty,56,Female,2024-02-28
4,B002,Book 2,Brandon Sanderson,Mystery,1991,Pearson,678,English,1,BR0422,M057,2026-02-16,2026-03-12,Member 57,Faculty,33,Male,2024-03-23

In [20]:
# Find the category with the highest and lowest number of borrowings. / Genre
highest_cat = borr_book['Genre'].value_counts(ascending=False).head(1)

lowest_cat = borr_book['Genre'].value_counts(ascending=True).head(1)

print(highest_cat, lowest_cat)

Genre
Mystery    512
Name: count, dtype: int64 Genre
Romance    81
Name: count, dtype: int64

In [21]:
# determine which members borrow books most frequently.
df_full['Name'].value_counts()

Name
Member 78     31
Member 147    24
Member 122    23
Member 126    23
Member 138    20
              ..
Member 80      6
Member 136     6
Member 29      5
Member 108     5
Member 121     4
Name: count, Length: 150, dtype: int64

In [22]:
# Compare borrowing activity between different membership types.
df_full['MembershipType'].value_counts() # students are most borrowing than others by far

MembershipType
Student    1197
Public      415
Faculty     289
Premium      99
Name: count, dtype: int64

In [23]:
# Analyze how borrowing changes across publication years.
print('Years with the most borrowed books:')
borr_book['PublicationYear'].value_counts().head()

Years with the most borrowed books:

PublicationYear
1989    108
2003    102
2019     96
1987     90
1990     86
Name: count, dtype: int64

In [24]:
# Identify the most popular authors.
df1['Author'].value_counts().head(3)

Author
J.K. Rowling     34
Alice Brown      32
George Orwell    30
Name: count, dtype: int64

In [25]:
# Find the books that have never been borrowed.
all_books = df1['BookID']
borrowed_books = df2['BookID']

never_borr_books = np.setdiff1d(all_books, borrowed_books)

never_borr_books

array(['B012', 'B013', 'B015', 'B031', 'B039', 'B044', 'B092', 'B125',
       'B129', 'B175', 'B181', 'B213', 'B242', 'B268', 'B294', 'B298',
       'B310', 'B317', 'B322', 'B337', 'B344', 'B348', 'B378'],
      dtype=object)

In [26]:
# Compare the average borrowing duration across genres.
borr_book['borrow_dur'] = borr_book['ReturnDate'] - borr_book['BorrowDate']

borr_book.groupby('Genre')['borrow_dur'].mean()

Genre
Biography         18 days 03:08:34.285714285
Business          17 days 04:33:43.140495867
Data Science      17 days 11:20:29.268292683
Fantasy           15 days 19:31:08.354430379
History           16 days 11:51:19.518072289
Mystery              16 days 22:24:22.500000
Programming       17 days 04:57:45.762711864
Romance           16 days 20:44:26.666666666
Science Fiction   17 days 19:05:03.614457831
Self Help         17 days 12:51:57.525773196
Name: borrow_dur, dtype: timedelta64[ns]

In [27]:
# Show the distribution of books across genres.
df1['Genre'].value_counts()

Genre
Business           52
Mystery            43
Data Science       43
Self Help          42
Biography          40
Programming        40
History            39
Science Fiction    35
Romance            34
Fantasy            32
Name: count, dtype: int64

In [28]:
# Analyze monthly borrowing trends (if borrowing dates are available).
df2['BorrowMonth'] = df2['BorrowDate'].dt.month

df2['BorrowMonth'].value_counts()

BorrowMonth
3     218
1     208
5     204
4     200
2     193
6     161
7     153
11    147
8     142
12    133
10    126
9     115
Name: count, dtype: int64

In [29]:
# Convert one or more numerical columns into NumPy arrays.
pages_array = df1['Pages'].to_numpy()

print(type(pages_array))

<class 'numpy.ndarray'>

In [30]:
df3

    MemberID        Name MembershipType  Age  Gender   JoinDate
0       M001    Member 1        Student   47    Male 2025-02-18
1       M002    Member 2         Public   47  Female 2022-02-14
2       M003    Member 3         Public   43  Female 2022-01-07
3       M004    Member 4        Student   65    Male 2025-03-30
4       M005    Member 5        Student   22    Male 2024-05-17
..       ...         ...            ...  ...     ...        ...
145     M146  Member 146        Student   46  Female 2024-05-31
146     M147  Member 147        Student   70    Male 2023-09-08
147     M148  Member 148        Student   38    Male 2024-09-08
148     M149  Member 149        Faculty   38    Male 2024-03-26
149     M150  Member 150        Faculty   38  Female 2025-07-20

[150 rows x 6 columns]

In [31]:
# Identify the highest and lowest values in a numerical column. (age)
age_array = df3['Age'].to_numpy()
print(f'the highest value in column Age is: {age_array.max()}')

the highest value in column Age is: 70

In [32]:
# Sort a NumPy array and display the result.
sorted_age_array = np.sort(age_array)
sorted_age_array

array([18, 18, 18, 19, 19, 19, 20, 20, 20, 20, 21, 21, 21, 22, 22, 22, 23,
       23, 24, 24, 24, 24, 24, 26, 26, 26, 27, 27, 27, 27, 28, 28, 29, 29,
       29, 29, 30, 31, 31, 31, 31, 31, 31, 32, 32, 32, 33, 33, 33, 33, 33,
       34, 34, 35, 35, 35, 35, 36, 37, 37, 37, 37, 37, 38, 38, 38, 38, 38,
       38, 39, 40, 40, 41, 41, 41, 42, 42, 42, 42, 42, 42, 43, 43, 44, 45,
       46, 46, 46, 47, 47, 47, 47, 49, 49, 49, 49, 50, 50, 51, 52, 52, 52,
       52, 53, 53, 53, 53, 53, 53, 53, 54, 54, 55, 56, 56, 56, 56, 56, 57,
       57, 57, 58, 59, 59, 59, 59, 59, 60, 61, 63, 63, 63, 64, 64, 64, 65,
       65, 65, 65, 66, 66, 66, 67, 67, 67, 69, 69, 70, 70, 70])

In [33]:
# Perform at least one vectorized calculation to create a new numerical result or metric.
age_month = age_array * 12
print(age_month)

[564 564 516 780 264 480 252 240 348 768 504 504 720 480 624 312 792 564
 504 564 420 240 804 372 672 672 780 552 372 600 840 672 444 612 444 636
 732 588 708 456 324 348 384 828 636 636 396 468 492 768 420 672 360 372
 216 780 396 396 504 708 408 588 828 372 528 384 408 324 384 396 708 792
 780 336 312 624 240 252 312 756 372 252 588 624 228 432 840 288 324 684
 420 492 648 444 708 516 636 696 276 708 288 372 240 624 456 660 264 648
 504 792 600 288 264 804 228 588 636 348 804 756 420 756 456 276 552 288
 348 636 228 636 672 216 504 396 336 444 324 540 444 492 768 684 288 216
 684 552 840 456 456 456]